// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package domain

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Course struct {
	ID          pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	TeacherID   pgtype.UUID
	StudentID   pgtype.UUID
	Title       pgtype.Text
	Description pgtype.Text
	Date        pgtype.Timestamptz
	Completed   bool
	Canceled    bool
}

type Student struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type Teacher struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Description pgtype.Text
	Picture     pgtype.Text
}

type User struct {
	ID           pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	PasswordHash []byte
	Activated    bool
	Version      int32
	Email        string
	Provider     string
	ProviderID   pgtype.Text
	Role         pgtype.Int2
}
